---

- name: add export of LIVBIRT_DEFAULT_URI to bashrc file
  shell: "echo 'export LIBVIRT_DEFAULT_URI=\"qemu:///system\"' >> ~/.bashrc"
  sudo_user: "{{ instack_user }}"
  sudo: yes

- name: enable the rdo-release repository
  yum: name="{{ rdo[ config.version ].instack_release_rpm[ ansible_distribution ] }}" state=present #"
  when: ansible_distribution == 'Fedora'

- name: install instack-undercloud
  yum: name=instack-undercloud state=latest
  when: config.instack_undercloud_rpm is not defined

- name: install updated version of instack-undercloud if it exists
  yum: name="{{ config.instack_undercloud_rpm }}"
  when: config.instack_undercloud_rpm is defined

- name: install libguestfs-tools
  yum: name=libguestfs-tools

- name: install systemd
  yum: name=systemd

- name: run script to install required dependencies
  shell: "cd {{ instack_user_home.stdout }}; export LIBVIRT_DEFAULT_URI=\"qemu:///system\" ; source /usr/libexec/openstack-tripleo/devtest_variables.sh; tripleo install-dependencies"
  ignore_errors: yes
  sudo_user: "{{ instack_user }}"
  sudo: yes

- name: run script to setup virtual environment
  register: instack_virt_result
  shell: "cd {{ instack_user_home.stdout }}; export LIBVIRT_DEFAULT_URI=\"qemu:///system\" ; instack-virt-setup"
  sudo_user: "{{ instack_user }}"
  sudo: yes

- name: start instack vm
  shell: "export LIBVIRT_DEFAULT_URI=\"qemu:///system\" ; sleep 5; virsh list --all; virsh start instack"
  sudo_user: "{{ instack_user }}"
  sudo: yes

- name: get ip address of instack vm
  shell: "sleep 10; cat /var/lib/libvirt/dnsmasq/default.leases | grep $(tripleo get-vm-mac instack) | awk '{print $3;}'"
  register: instack_ip_address
  sudo_user: "{{ instack_user }}"
  sudo: yes

- name: get mac addresses for overcloud nodes
  shell: "for i in $(seq 0 3); do echo -n $(tripleo get-vm-mac baremetal_$i) \" \"; done; echo"
  register: overcloud_node_ips
  sudo_user: "{{ instack_user }}"
  sudo: yes

- name: print overcloud_node_ips
  debug: var=overcloud_node_ips.stdout

- name: get instack vm ip address
  shell: >
     chdir={{ instack_user_home.stdout }}
     cat /var/lib/libvirt/dnsmasq/default.leases | grep $(tripleo get-vm-mac instack) | awk '{print $3;}'
  sudo_user: "{{ instack_user }}"
  sudo: yes
  register: instack_vm_ip_result

- name: print instack_vm_ip_result
  debug: var=instack_vm_ip_result.stdout

- name: copy keys from root user
  shell: "cat /root/.ssh/authorized_keys >> {{ instack_user_home.stdout }}/.ssh/authorized_keys"

- name: install sshpass for tunnel
  yum: name=sshpass state=present

- name: open ssh tunnel to instack vm on port {{ config.vm_ssh_port }}
  shell: "sudo iptables -I INPUT -p tcp --dport {{ config.vm_ssh_port }} -j ACCEPT; sshpass -p {{ config.pass }} ssh -o \"StrictHostKeyChecking no\" -g -N -L {{ config.vm_ssh_port }}:{{ instack_vm_ip_result.stdout }}:22 `hostname` &"
  register: tunnel_port_output
  sudo_user: "{{ instack_user }}"
  sudo: yes
  async: 36000
  poll: 0
