---
- name: getenforce
  command: getenforce
  register: result

- debug: msg="Setting SELINUX to {{distro.config.selinux|default('permissive')}}"   #"
  when: result.stdout|capitalize != distro.config.selinux|default('permissive')|capitalize

- selinux: policy=targeted state={{distro.config.selinux|default('permissive')}}
  when: result.stdout|capitalize != distro.config.selinux|default('permissive')|capitalize

- selinux: policy=targeted state=permissive
  when: ansible_distribution == 'Fedora'

- name: getenforce
  command: getenforce
  register: result

- debug: msg="SELINUX currently set to {{ result.stdout }}"  #"

#TO-DO: removed openstack-selinux-test, check w/ lhh for updates
