---
dependencies:
    - { role: common }
    - { role: packstack/common }
    - { role: product/rdo/common }
    - { role: product/rdo/rhel, when: ansible_distribution == 'RedHat' }
    - { role: product/rdo/rhel, when: ansible_distribution == 'CentOS' }
    - { role: product/rdo/fedora, when: ansible_distribution == 'Fedora' }

