---
# setup packstack prerequisites
- name: Setup openstack repos
  hosts: openstack_nodes
  gather_facts: yes
  sudo: yes
  tasks:
      - name: Disable any existing repos
        shell: sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/*
        register: shell_result
        changed_when: "shell_result.rc == 0"
        failed_when: "shell_result.rc > 2"

      - name: Install release tool on machines
        command: "yum localinstall -y {{ product.rpmrepo[ansible_distribution] }}/{{ product.name }}-release-latest.noarch.rpm"

      - name: Execute the release tool
        shell: "{{ product.name }}-release {{ product.version|int }}"
        register: shell_result
        changed_when: "shell_result == 0"

- name: Get build details
  hosts: controller
  sudo: no
  roles:
    - build_mark/build
