---
- name: yum install rdo-release for EL environment
  yum: name="{{ product.rpm[ ansible_distribution ] }}" state=present     #"
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: disable foreman repo
  command: |
      sed -i -e "s/enabled=.*/enabled=0/g" /etc/yum.repos.d/foreman.repo

- name: disable gpgcheck for rdo for every non production repo
  lineinfile:
    dest=/etc/yum.repos.d/rdo-release.repo
    regexp=^gpgcheck=1
    line=gpgcheck=0
  when: product.repo_type != 'production'

- name: set baseurl for rdo for EL environment
  lineinfile:
    dest=/etc/yum.repos.d/rdo-release.repo
    regexp=^baseurl=
    line="baseurl={{ product.repo[product.repo_type][ansible_distribution][ansible_distribution_version] }}"
  notify:
    - Yum clean all

- name: List available yum repositories
  command: yum -d 9 repolist
  register: result

- name: Print repolist
  debug: var=result.stdout_lines
