---
#python-backports is installed as a dep for cloud-init
- name: Remove python-backports if installed
  yum: name=python-backports state=removed

- name: Create the RHOS poodle repositories for RHEL
  template: src=rhos_poodle.repo.j2 dest=/etc/yum.repos.d/rhos_poodle.repo
  notify:
    - Yum clean all

- name: List available yum repositories
  command: yum -d 9 repolist
  register: result

- name: Print repolist
  debug: var=result.stdout_lines