- name: Provision nodes
  ec2:
       key_name: "{{ provisioner.key_name }}"
       instance_type: "{{ item.value.flavor_id }}"
       region: "{{ item.value.region }}"
       image: "{{ item.value.image_id }}"
       wait: yes
       group: default
       count: 1
  register: new_nodes
  with_dict: nodes

- name: debug
  debug: var=new_nodes

#ami-a8d369c0 rhel70
#ami-1643ff7e works rhel65