- name: cleanup git repo prior to running tests
  command: git clean -qdffx
  args:
    chdir: testbed/{{component_basename}}

- name: create new logs dir
  file: path={{ansible_env.HOME}}/testbed/logs/ state=directory

- name: Run test using only installed packages
  shell: >
    source ~/testbed/venv/bin/activate;
    python setup.py egg_info;
    python -m nova.openstack.common.lockutils
          python setup.py testr --testr-args='--subunit --concurrency 0  '
      | subunit2junitxml --output-to=../logs/testresult.xml -f
      | subunit-2to1 | tools/colorizer.py >../logs/testrun.log 2>&1

  args:
    chdir: testbed/{{component_basename}}
    executable: /bin/bash
  register: test_run
  ignore_errors: yes

- name: copy test results to logs dir
  fetch: src={{ansible_env.HOME}}/testbed/logs/{{item}}
         dest=../../logs/ flat=yes
  with_items:
      - testresult.xml
      - testrun.log

