- name: load rpms needed to run test in virtualenv
  include_vars: "{{component.name}}.yml"

### TODO: may be include_vars: '{{ component.name }}/{{ ansible_distribution ... }}'

- name: install rpms needed for virtualenv run
  yum: pkg={{item}} state=present
  sudo: yes
  with_items: virtenv.rpm.install

- name: cleanup git repo prior to running tests
  command: git clean -qdffx
  args:
    chdir: "{{component_path}}"

- name: going to run tests in virtualenv
  debug: msg="--------------------------------------"

- pause: seconds=2

- name: run test in virtualenv (no junitxml)
  shell: >
    {{test_env.venv.run.replace('\n', '')}}
  args:
    chdir: "{{component_path}}"
    executable: /bin/bash
  register: venv_testrun
  ignore_errors: yes

- name: copy virtualenv test results to logs dir
  fetch: src="{{component_path}}/{{item}}"
         dest=../../logs/ flat=yes
  with_items: test_env.venv.archive
