- name: print component testbed path
  debug: var=component_path

- name: cleanup git repo prior to running tests
  command: git clean -qdffx
  args:
    chdir: "{{component_path}}"

- name: create new logs dir
  file: path={{ansible_env.HOME}}/testbed/logs/ state=directory

- name: print the test run command
  debug: var=test_env.rpm.run

- name: Run test using only installed packages
  shell: >
    source ~/testbed/venv/bin/activate;
    {{test_env.rpm.run.replace('\n', '')}}
  args:
    chdir: "{{component_path}}"
    executable: /bin/bash
  register: test_run
  ignore_errors: yes

- name: copy test results to logs dir
  fetch: src="{{component_path}}/{{item}}"
         dest=../../logs/ flat=yes
  with_items: test_env.rpm.archive

