---

- name: get neutron subnet name
  shell: >
    chdir={{ instack_user_home.stdout }}
    source {{ instack_user_home.stdout }}/stackrc;
    neutron  subnet-list -f csv -F id --quote none | grep -v '^id$' | tail -n 1
  register: neutron_subnet_name

- name: print neutron subnet name
  debug: var=neutron_subnet_name.stdout

- name: change dns nameserver on neutron subnet
  shell: >
    chdir={{ instack_user_home.stdout }}
    source {{ instack_user_home.stdout }}/stackrc;
    neutron subnet-update --dns-nameserver {{ job.internal_nameserver_ip_address }} {{ neutron_subnet_name.stdout }}
