---
- name: Install rpm deps for source-based tempest
  hosts: tester
  gather_facts: no
  sudo: yes
  tasks:
      #TODO(tkammer): move the list of packages to khaleesi-settings
    - name: Install support packages for pip-based deps building
      yum: name={{ item }} state=present
      with_items:
        - facter
        - gcc
        - git
        - libffi-devel
        - libxml2-devel
        - libxslt-devel
        - mariadb-devel
        - openssl-devel
        - python-virtualenv
    - command: easy_install pip

- name: Install tempest from source
  hosts: tester
  gather_facts: no
  tasks:
    - git: repo={{ tester.git.repo }} version={{ tester.git.revision }}
           dest={{ tester.dir }}
      register: tempest_repo

    - command: chdir={{ tester.dir }} git log -1 --pretty=format:%h
      register: tempest_repo_version

    - debug: "msg='Build mark: tempest={{ tempest_repo_version.stdout }}'"

    - name: install virtualenv
      command: "python {{ tester.dir }}/tools/install_venv.py {{ tester.dir }}"
      when: tempest_repo|changed

      #TODO(tkammer): move this to khaleesi-settings
    - name: prepare list of extra/specific pip pkgs to install
      copy:
        dest: "{{ tester.dir }}/extra-requirements.txt"
        content: |
          junitxml
          unittest2
          nose
          python-ceilometerclient==1.0.10 # fix: tempest failure
      register: extra_reqs

    - name: pip install extra requirements
      pip: requirements="~/{{ tester.dir }}/extra-requirements.txt" state=present virtualenv="~/{{ tester.dir }}/.venv"
      when: tempest_repo|changed or extra_reqs|changed
