---
- name: Remove openstack-foreman-installer rpm - Source
  yum: name={{ openstack_foreman_installer_rpm }} state=absent

- name: Ensure git is installed
  yum: name=git state=latest

- name: Get astapor repo
  git: repo={{ job.astapor_repo }}
       dest={{ astapor_dest }}
       version={{ job.astapor_branch }}

