---
# provison
- include: dump_settings.yml
#determine provisioner and whether or not to skip
- include: group_by_provision.yml

- include: provision.yml
- include: group_by.yml tags=provision

# prep
#- include: ../workarounds/workarounds-pre-prep.yml tags=workaround

- name: selinux
  sudo: yes
  hosts: all:!localhost
  tags: prep
  roles:
    -  selinux_check

- include: packstack/setup-ssh-keys.yml tags=prep
- include: prep.yml

- name: Prepare network for Packstack install
  sudo: yes
  hosts:
    - controller
    - compute
    - tester
    - networker
  tags: prep
  roles:
    -  network-setup

- include: validate_nodes.yml

- name: Debug list config variables
  hosts: local
  sudo: no
  tags: provision
  roles:
    - { role: packstack/debug }

- name: Get build details
  hosts: controller
  sudo: no
  roles:
    - { role: build_mark/build }

# apply pre-packstack workarouds
- include: ../workarounds/workarounds-prep.yml tags=workaround

- name: Setup packstack dependencies on nodes (rdo)
  hosts: openstack_nodes:&rdo
  sudo: yes
  roles:
      - product/rdo
  tags: prep

- name: Setup packstack dependencies on nodes (rhos)
  hosts: openstack_nodes:&rhos
  sudo: yes
  roles:
      - product/rhos
  tags: prep

- name: Setup packstack on Controller
  hosts: controller
  sudo: yes
  roles:
      - product/packstack
  tags: prep

# Generate answers
- name: Setup packstack on Controller
  hosts: controller
  sudo: yes
  roles:
      - packstack/generate-answers
  tags: prep

- include: ../workarounds/workarounds-pre-run-packstack.yml tags=workaround

# packstack_run

- name: Run packstack
  hosts: controller
  sudo: yes
  roles:
    - { role: packstack/runner }
  tags: packstack_run

- include: ../workarounds/workarounds-post-run-packstack.yml tags=workaround

- name: Create external network
  hosts: controller
  roles:
    - { role: openstack/create-external-network }

- name: Get Status after reboot
  hosts: controller
  sudo: yes
  tags: packstack_run
  roles:
    - { role: openstack/openstack-status }

- name: Upgrade from GA to latest poodle
  hosts: all:!localhost:&RedHat:&rhos
  sudo: yes
  tags: packstack_run
  roles:
    - { role: upgrade }

# sahara
- include: sahara.yml

# storage
- include: storage.yml

# tempest
- name: List ip address of tempest node
  hosts: tester
  sudo: yes
  roles:
    - { role: tempest/iptables/node_data }
  tags: tempest_setup

- name: Ensure iptables is open for tempest
  hosts: all:!localhost:!tester
  sudo: yes
  roles:
    - { role: tempest/iptables }
  tags: tempest_setup

- include: tempest.yml

- name: Search for possible problems happened.
  hosts: all:!localhost:!tester
  sudo: yes
  roles:
    - { role: build_mark/search_problems }

- name: Produce build marks summaries
  hosts: localhost
  roles:
    - { role: build_mark/summary }

- name: clean up
  hosts: all:!localhost:!tester
  sudo: yes
  roles:
    - { role: linux/rhsm }
