---
- name: set baseurl for rdo if stage
  lineinfile:
    dest=/etc/yum.repos.d/rdo-release.repo
    regexp=^baseurl=
    line="baseurl={{ product.repo[product.repo_type][ansible_distribution][ansible_distribution_version] }}"
  when: product.repo_type == 'stage'
  notify:
    - Yum clean all

- name: disable gpgcheck for rdo if not distribution-repo
  lineinfile:
    dest=/etc/yum.repos.d/rdo-release.repo
    regexp=^gpgcheck=1
    line=gpgcheck=0
  when: product.repo_type not in ('production', 'distribution')

- name: List available yum repositories
  command: yum -d 7 repolist
  register: result

- name: Print repolist
  debug: var=result.stdout_lines

